---
name: "Pull Request Labeler"
on:  # yamllint disable-line rule:truthy
  pull_request_target:
    types: [opened, reopened]
    branches: ["main", "master", "stable"]

# Declare default permissions as none.
permissions: {}

jobs:
  triage:
    permissions:
      actions: read
      contents: read
      packages: none
      pull-requests: write
      security-events: none
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
      with:
        repo-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}
