---
name: "Pull Request Labeler"
on:  # yamllint disable-line rule:truthy
  pull_request_target:
    types: [opened, reopened]
    branches: ["main", "master", "stable"]

# Declare default permissions as none.
permissions: {}

jobs:
  triage:
    permissions:
      actions: read
      contents: read
      packages: none
      pull-requests: write
      security-events: none
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
      with:
        repo-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}
